name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: "npm"
      - run: npm install
      - run: |
          if [ -n "${GITHUB_PAGES_BASE_PATH}" ]; then
            echo "Using provided base path: ${GITHUB_PAGES_BASE_PATH}"
          elif [[ "${GITHUB_REPOSITORY##*/}" != "${GITHUB_REPOSITORY_OWNER}.github.io" ]]; then
            echo "GITHUB_PAGES_BASE_PATH=/${GITHUB_REPOSITORY##*/}" >> $GITHUB_ENV
          else
            echo "GITHUB_PAGES_BASE_PATH=" >> $GITHUB_ENV
          fi
          npm run build
        env:
          GITHUB_PAGES_BASE_PATH: ${{ secrets.GITHUB_PAGES_BASE_PATH }}
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v5
        with:
          path: out

  deploy:
    needs: build
    runs-on: ubuntu-latest
    permissions:
      pages: write
      id-token: write
    environment:
      name: github-pages
      url: ${{ steps.pages-deployment.outputs.page_url }}
    steps:
      - name: Deploy to GitHub Pages
        id: pages-deployment
        uses: actions/deploy-pages@v5
